version: 1
policy:
  pullRequests: collaborators
tasks:
  $let:

    project_name:
      autobisect

    matrix:
      language: python
      secrets:
        - type: env
          secret: project/fuzzing/codecov-autobisect
          name: CODECOV_TOKEN
          key: token
      script:
        - bash
        - '-xec'
        - tox; tox -e codecov
      jobs:
        include:
          - name: tests python 3.8 (linux)
            version: "3.8"
            env:
              TOXENV: py38,lint
          - name: tests python 3.9 (linux)
            version: "3.9"
            env:
              TOXENV: py39,lint
          - name: tests python 3.10 (linux)
            version: "3.10"
            env:
              TOXENV: py310,lint
          - name: test python 3.10 (windows)
            version: "3.10"
            platform: windows
            env:
              TOXENV: py310
            script:
              - bash
              - '-xec'
              - python -m pip install --user pipx;
              - python -m pipx ensurepath;
              - pipx install poetry;
              - tox;
              - tox -e codecov;
          - name: tests python 3.11 (linux)
            version: "3.11"
            env:
              TOXENV: py311,lint
          - name: semantic-release
            version: "3.10"
            script:
              - bash
              - '-xec'
              - >-
                git config --global user.email "autobisect@mozilla.com";
                git config --global user.name "semantic-release";
                git fetch origin master --tags;
                git checkout -b master;
                tox -e release
            when:
              branch: master
              all_passed: true
            secrets:
              - type: env
                secret: project/fuzzing/pypi-autobisect
                name: TWINE_USERNAME
                key: username
              - type: env
                secret: project/fuzzing/pypi-autobisect
                name: TWINE_PASSWORD
                key: password
              - type: key
                secret: project/fuzzing/deploy-autobisect
                key: key

  in:
    $if: >
      (tasks_for == "github-push")
      || (tasks_for == "github-pull-request" && event["action"] in ["opened", "reopened", "synchronize"])
      || (tasks_for == "github-release" && event["action"] in ["published"])
    then:
      - created: { $fromNow: '' }
        deadline: { $fromNow: '1 hour' }
        provisionerId: proj-fuzzing
        workerType: ci
        payload:
          features:
            taskclusterProxy: true
          maxRunTime: 3600
          image:
            type: indexed-image
            path: public/orion-decision.tar.zst
            namespace: project.fuzzing.orion.orion-decision.master
          env:
            PROJECT_NAME: ${project_name}
            CI_MATRIX: { $json: { $eval: matrix } }
            GITHUB_EVENT: { $json: { $eval: event } }
            GITHUB_ACTION: ${tasks_for}
            TASKCLUSTER_NOW: ${now}
          command:
            - ci-decision
            - -v
        scopes:
          - queue:create-task:highest:proj-fuzzing/ci
          - queue:create-task:highest:proj-fuzzing/ci-*
          - queue:scheduler-id:taskcluster-github
          - secrets:get:project/fuzzing/codecov-autobisect
          - secrets:get:project/fuzzing/deploy-autobisect
          - secrets:get:project/fuzzing/pypi-autobisect
        metadata:
          name: ${project_name} ci decision
          description: schedule ci tasks for ${project_name}
          owner: '${event.sender.login}@users.noreply.github.com'
          source: https://github.com/MozillaSecurity/autobisect
    else: [ ]
