sudo: false
group: travis_latest
language: python
cache: pip
matrix:
  fast_finish: true
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "nightly"
  allow_failures:
    - python: "nightly"
before_install:
  - git clone https://github.com/MozillaSecurity/ffpuppet
install:
  # Already in venv, no need for --user
  - travis_retry python -m pip install --upgrade setuptools pip
  - travis_retry python -m pip --version
  - travis_retry python -m pip install --upgrade ffpuppet/  # Needs the trailing slash to refer to the cloned directory
  - travis_retry python -m pip install --upgrade .[test]  # Installs python testing-related packages
  # The current working dir has to be the current autobisect/ directory for this "-r" to work
  - travis_retry python -m pip install --upgrade -r requirements.txt  # Gets ffpuppet, lithium-reducer from GitHub
  - python -m flake8 --version
script:
  - python -m pytest autobisect/
