dist: bionic
os: linux
group: travis_latest
language: python
cache: pip
jobs:
  fast_finish: true
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "nightly"
  allow_failures:
    - python: "nightly"
env:
  global:
    secure: "JrXLZAIkW2O2rUtUm5aZeIWTYXk6KX42aKb53NzJn2OGG/UVG7+Z+VxO8tYSPlfpH3svDyBoUM2+XuCjMSV8Qxhod3NXiunzf+f45kQEbAEn2MbKP8sb5PqYegg9CqFzzxogBcS/r0Bdrg1347V71qd5Wm3RwZSiBsoDT5StrfDR+7vJUvRouKXVcYz3ktYHPD1nChoug2/PqydCUpeAlQS6b33ttFmSYuDtOgJPNIq9rcchfJKp38/7n7bSA9weWODBv1b7+TTF3tN5++Kr0Lg6v4DdvwWGtu1wFmDXnrFnlseubW+bfxzzcvq7DWPHYBepwGHoBmEaimsBRcxGzLcTiAV7NPMfGWbI3jRfl+cevvBVNlfIEXsuOsVQcAD/UO6XSFvN4VgUnAkDCj/Y2/XJedJYouUOhj6ZYAw23Ia7wP4Ad5Z/F9A4S6uoTYc0yC9roonXB62DXwb7D/4s4ZmNwXmwFlB7hxKkpqw5CNp6G9mCv2Wqvq4SjhDFbFP1mv9cvoF1gaaF/0H76RNOFUOTosOO7C6Ts1obyJynn5gKiRcQkK6dPfX02LLFsfz/qsKjZKC4dbUwpfAYuixYclt6WmH4zoaJTVW+pG+yF1ya7NEnB5f3c6qXLmWwd+Jc3Li7shaYMnXz3p2A6ZMzCN7yy2TSGOc4s4MvzBtl5oQ="
before_install:
  - pip install poetry
install:
  - poetry install -vvv
script:
  - python -m pytest
before_deploy:
- poetry config http-basic.pypi mozillasecurity $PYPI_PASS
- poetry build
deploy:
  - provider: script
    script: poetry publish
    on:
      branch: master
      tags: true
      os: linux
      python: 3.8
