dist: bionic
os: linux
group: travis_latest
language: python
cache: pip
jobs:
  fast_finish: true
  include:
  - python: '3.6'
  - python: '3.7'
  - python: '3.8'
  - python: nightly
  allow_failures:
  - python: nightly
before_install:
- pip install poetry
install:
- poetry install -vvv
script:
- python -m pytest
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
- poetry build
deploy:
- provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    branch: master
    tags: true
    os: linux
    python: 3.8
env:
  global:
  - secure: KHj7OUyrDtyISg/OyypIdrB5ea1ndw7FFFR51pKJHQGidfJOSFlVFgMnqeuH6B6YeA1nW2c4dgUt5GQjAE+gWw8gpq8igaGL+dNzWUuypT9wH507t29mVBOTQHjNp6R0KcIYtL92XRMw11j6BRiqI4ZmC+LseD8nN7b3NEyxpPgglwjHJREfTVA08vEqEBUmj9cE7OHzA6kNJ2uKZsPorPwOmv9hFEvXsCeVG1rhTt/IDfx34GbYSf0BfeZ9eRt1Hn6rRb2hwAyDoF2mINtAkozmQelRDGW2N4nAl6zgBwvsZDZH0VebXtH7tUJpO+0Hhm0HdJABh1c3HpxRiIIOkerhVMZxGLix6cGW3XqOM5t989gYxgyWSeBcEkPazvoA5H2spQHLG3eBdF938p5HtztBgUq5m7/GQMft2TWBRsCqZm9FqAYTYZo6BQpDw6KKPHFHpzYGYGBqc3Rc+T32V453UnAA+f7C1BfAkjg7f5wYbfOPGHVdIFSoymh2mGBxFeWFufUdHBT/Gc7rjBvTkULmt9OnhK42g/8o/r/hQPH1UL7H5lZUu3R6z80eRujM/fhsxHwYfefcgLun/iYqPs2WwaITqF4hS8bQGLfo3d+d7M9kiX5Ds6eQnJmUwj8NU92dYssD2TyiCtw4GIgS088p/5IVTEak4BDil3iBggE=
  - secure: Ziu7vlYOLpsaPT3lcc5kn0TgVoXMBDWb7oBHkuKg29KLVVvb/3UShOa6nWkONI7YcbDy/GVZ+kwZrN5JCnQeAEBjwZQF/X5qllqxoTIpuRi1+tK49MVThRFT6Ni+E9Euf9SS+lAIQrOwwNIk8MEMm1zWUxRIPbztgAVtmqvoWo+8SbMNYfJeA/pDYS/ZbuGcIutnNV8W446IZI6io1N3hiCviMmtp6jBMQTVUzuVlbKom9ZghTFpC+94lGFEdz9vXObpi1jv6Pdg8dvcnd8lAqYcDWlq6fWvN4JJpowW1orHUimj1Xbr0elQz97eYfrESeFropt0wAywHtwxfyw7kFAmjG8quFyJ4EIFN6sISNnC2tWKHaFJiRUsQW5qSvMJA7IUrGHkgH8p1OzCMW+cywel8+pk3z8E8aaLBdvXFomy1XWTNDpncUY2Ej7cJsFlB8A4rVUtg9dpMhrZKgKx87i7JkKWScNbSL4B+pLkAggw9XnTUWykSnf3sBS2/GdVG1KEqyj9bF5p35wUr5D2EIKnDZz6S5rBgMAhlJES8SL+rLwDavxlS5HZTrJPIfHh8q9nUFfhVpE+aoIB5gpAaFIqvQMx+/EsEbT0gCzAH6Tazp9dt6WNM5YGFeWN+dM/SOtOp1OeFNHpIlX22yyAocRmLUtNm2ecc+HQcr1ISaA=
