sudo: false
group: travis_latest
language: python
cache: pip
matrix:
  fast_finish: true
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "nightly"
  allow_failures:
    - python: "nightly"
before_install:
  - travis_retry pip install poetry
install:
  - travis_retry poetry install
script:
  - python -m pytest autobisect/
